#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { parseCanonicalDsl } from "./canonical/parser";
import { normalizeCanonicalRecord } from "./canonical/normalize";
import { validateCanonicalJson } from "./canonical/validator";
import { emitCanonicalSql } from "./canonical/sqlEmitter";
import { toErrorPayload, CanonicalError } from "./canonical/errors";

function getArgValue(flag: string, args: string[]): string | undefined {
  const index = args.findIndex((arg) => arg === flag);
  if (index === -1) {
    return undefined;
  }
  return args[index + 1];
}

function ensureArg(flag: string, args: string[]): string {
  const value = getArgValue(flag, args);
  if (!value) {
    throw new CanonicalError("E_PARSE_ARGS", `Missing required arg: ${flag}`);
  }
  return value;
}

function printHelp(): void {
  console.log(`canonical CLI (v1)\n
Commands:
  canonical parse --in <dsl-file> [--out <json-file>]
  canonical validate --in <json-file> --schema <schema-file>
  canonical emit-sql --in <json-file> --out <migration.sql>
  canonical scaffold-frontend --in <json-file> --target <project-dir>
`);
}

function scaffoldFrontend(targetDir: string): void {
  const directories = [
    "src/features/canonical-input",
    "src/features/canonical-review",
    "src/features/canonical-iam",
    "src/features/canonical-timeline",
    "src/shared/schema",
    "src/shared/validation"
  ];

  for (const dir of directories) {
    const absolute = path.resolve(targetDir, dir);
    fs.mkdirSync(absolute, { recursive: true });
    const marker = path.join(absolute, "README.md");
    if (!fs.existsSync(marker)) {
      fs.writeFileSync(
        marker,
        `# ${dir}\n\nScaffold generated by canonical scaffold-frontend.\n`,
        "utf8"
      );
    }
  }
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const command = args[0];

  if (!command || command === "--help" || command === "-h") {
    printHelp();
    return;
  }

  if (command === "parse") {
    const inputPath = path.resolve(ensureArg("--in", args));
    const outPath = getArgValue("--out", args);

    const dsl = fs.readFileSync(inputPath, "utf8");
    const parsed = parseCanonicalDsl(dsl);
    const normalized = normalizeCanonicalRecord(parsed);

    if (outPath) {
      const absoluteOut = path.resolve(outPath);
      fs.mkdirSync(path.dirname(absoluteOut), { recursive: true });
      fs.writeFileSync(absoluteOut, JSON.stringify(normalized, null, 2), "utf8");
      console.log(`Parsed canonical payload written to ${absoluteOut}`);
      return;
    }

    console.log(JSON.stringify(normalized, null, 2));
    return;
  }

  if (command === "validate") {
    const inputPath = path.resolve(ensureArg("--in", args));
    const schemaPath = path.resolve(ensureArg("--schema", args));

    const payload = JSON.parse(fs.readFileSync(inputPath, "utf8"));
    validateCanonicalJson(payload, schemaPath);
    console.log("Schema validation passed.");
    return;
  }

  if (command === "emit-sql") {
    ensureArg("--in", args);
    const outputPath = path.resolve(ensureArg("--out", args));
    emitCanonicalSql(outputPath);
    console.log(`SQL migration emitted to ${outputPath}`);
    return;
  }

  if (command === "scaffold-frontend") {
    ensureArg("--in", args);
    const target = path.resolve(ensureArg("--target", args));
    scaffoldFrontend(target);
    console.log(`Frontend scaffolding generated at ${target}`);
    return;
  }

  throw new CanonicalError("E_PARSE_ARGS", `Unknown command: ${command}`);
}

main().catch((error) => {
  const payload = toErrorPayload(error);
  console.error(JSON.stringify(payload, null, 2));
  process.exit(1);
});
